#name:
#  users_microservices
server:
  port: 8081
spring:
  application:
    name: users
  r2dbc:
    url: r2dbc:postgresql://127.0.0.1:5432/users
    username: postgres
    password: admin
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
    registerWithEureka: true
    fetchRegistry: true