name:
  sells_microservice
server:
  port: 8084
spring:
  application:
    name: sells_microservice
  r2dbc:
    url: r2dbc:postgresql://172.17.0.2:5432/sells
    username: postgres
    password: admin
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8087/eureka