server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: users
          uri: http://users
          predicates:
            - Path=/users/**
        - id: sells
          uri: http://sells
          predicates:
            - Path=/sells/**
        - id: costs
          uri: http://costs
          predicates:
            - Path=/costs/**
        - id: products
          uri: http://products
          predicates:
            - Path=/products/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka